# Generated by Django 5.0.4 on 2024-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
