# Generated by Django 5.0.4 on 2024-04-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
