# Generated by Django 5.0.4 on 2024-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_service_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
